### ISSUE TITLE
Availability on Maven Central?

### ISSUE THREAD

**Issue by roberthunt** [freenowtech/spring-multirabbit#40]
Are there plans to publish the project to Maven Central under the new Maven coordinates (com.free-now.multirabbit)? Also is there a repository that can be used to obtain it in the meantime, I couldn't see anything in the documentation?

Thanks!

**Comment by rwanderc** [comment]
Currently it's published using bintray, which syncs with Maven Central.
Current latest version 2.3.0 is [available there](https://mvnrepository.com/artifact/com.free-now.multirabbit/spring-multirabbit). 
However, with bintray's shutdown happening soonish, we need to move to other solution.
Not sure yet if directly in Maven Central though.

**Comment by ocristian** [comment]
Hi @roberthunt.
We started to publish on maven central. Releases v.2.2.4, v2.3.6 and v2.4.0 can be found there already.
