### ISSUE TITLE
Provide CI skip functionality for releases

### ISSUE THREAD

**Issue by rwanderc** [freenowtech/spring-multirabbit#57]
Github Actions must skip release commits (prefixed with `[maven-release-plugin]`) to avoid building unnecessary and partial versions.

**Comment by sergioasantiago** [comment]
This can be done by adding [this](https://github.com/freenowtech/sauron/blob/main/.github/workflows/release-components.yml#L10) if line to your workflow.

**Comment by ocristian** [comment]
Hi @rwanderc, @sergioasantiago 
This is already managed on PR #64.

**Comment by ocristian** [comment]
Fixed on releases v2.2.4, v2.3.6 and v2.4.0.
