### ISSUE TITLE
what is the default acknowledge-mode definition

### ISSUE THREAD

**Issue by liuenci** [freenowtech/spring-multirabbit#71]
The default confirmation mechanism of this component is to automatically confirm ACK or manually confirm ACK?

**Comment by rwanderc** [comment]
Hi @liuenci, that must be provided in Spring Boot documentation.
Spring MultiRabbit plugs into the default the way Spring builds `CachingConnectionFactory`, having then this property defined by the framework. In SP 2.5, it's defined [here](https://github.com/spring-projects/spring-boot/blob/2.5.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitAutoConfiguration.java#L114), but it might be different in other versions.
